# Generated by Django 2.2.2 on 2019-06-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=200)),
                ('kittu', models.CharField(max_length=2000)),
            ],
        ),
    ]
